### ISSUE TITLE
Using ol3-my-location without node

### ISSUE THREAD

**Issue by HichamZouarhi** [itjope/ol3-my-location#2]
Hi, I wanted to display the heading of my position on an ol3 map without having to rotate the view so I found your solution. I've been looking for a js file to import something like ( ol-my-location.js ) but I haven't found it. Is there a way to use your ol3-my-location without node and npm install ?

**Comment by itjope** [comment]
Hi,
I tried to generate a browser package with Browserify but dit not get it to work. The problem seems to be that OpenLayers will be included twice - first in the main map application and then again in the package generated by Browserify.
