### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by uprel** [itjope/ol3-my-location#3]
I want to test your plugin but having all sorts of issues with npm and webpack. Seems like there are new versions out there and config doesn't work. Is there any updated documentation or if you can provide simply just a builded javascript file from your app.js

**Comment by itjope** [comment]
I have updated the documentation with a getting started example using the Parcel bundler.

https://github.com/itjope/ol3-my-location#quick-start-using-parcel-web-application-bundler

**Comment by uprel** [comment]
Thanks, that worked. I had to update node version to 8 and also parcel must be running on https if using Chrome, otherwise location is not allowed.
Like this: parcel index.html --https
